# Generated by Django 4.2.1 on 2023-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcsvdataproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test_table',
        ),
    ]
