# Generated by Django 4.2.1 on 2023-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcsvdataproject', '0002_alter_test_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_booth_number', models.IntegerField()),
                ('polling_booth_name', models.CharField(max_length=100)),
                ('parent_constituency', models.CharField(max_length=100)),
                ('winner_2014', models.CharField(max_length=100)),
                ('runnerup', models.CharField(max_length=100)),
                ('margin_percente', models.FloatField()),
                ('margin', models.IntegerField()),
                ('total_voter', models.IntegerField()),
                ('bjp_votes', models.IntegerField()),
                ('bjp_percente_votes', models.FloatField()),
                ('inc_votes', models.IntegerField()),
                ('inc_percente_votes', models.FloatField()),
                ('winner_2019', models.CharField(max_length=100)),
                ('margin_percente_2', models.FloatField()),
                ('margin_2', models.IntegerField()),
                ('total_voter_2', models.IntegerField()),
                ('bjp_votes_2', models.IntegerField()),
                ('bjp_percente_votes_2', models.FloatField()),
                ('inc_votes_2', models.IntegerField()),
                ('inc_percente_votes_2', models.FloatField()),
            ],
            options={
                'db_table': 'PPA Booth Analysis AC Arvi',
            },
        ),
    ]
