# Generated by Django 4.2.1 on 2023-08-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcsvdataproject', '0003_booth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booth',
            table='main_table',
        ),
    ]
