# Generated by Django 4.2.1 on 2023-08-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcsvdataproject', '0004_alter_booth_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
