# Generated by Django 4.2.1 on 2023-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcsvdataproject', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegtration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nid', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
